/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.5
** This class was generated on 27/08/2021 16:39:34
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using SSXImport.Data;
using SSXImport.Data.Interfaces;
using SSXImport.Business.Interfaces;

namespace SSXImport.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLTemplateFilterDetail.
	///</Summary>
	public partial class BLTemplateFilterDetail : SSXImport_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _templateFilterDetailId;
		protected string _templateFilterDetailGUID;
		protected Int32? _templateId;
		protected Int32? _templateTableDetailId;
		protected string _filterColumn;
		protected Int32? _filterOperator;
		protected string _filterValue;
		protected bool? _isActive;
		protected bool? _isDelete;
		protected Int32? _enteredBy;
		protected DateTime? _enteredDate;
		protected Int32? _updatedBy;
		protected DateTime? _updatedDate;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLTemplateFilterDetail()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 templateFilterDetailId
		///</parameters>
		public BLTemplateFilterDetail(Int32 templateFilterDetailId)
		{
			try
			{
				DLTemplateFilterDetail dlTemplateFilterDetail = DLTemplateFilterDetail.SelectOne(templateFilterDetailId);
				_templateFilterDetailId = dlTemplateFilterDetail.TemplateFilterDetailId;
				_templateFilterDetailGUID = dlTemplateFilterDetail.TemplateFilterDetailGUID;
				_templateId = dlTemplateFilterDetail.TemplateId;
				_templateTableDetailId = dlTemplateFilterDetail.TemplateTableDetailId;
				_filterColumn = dlTemplateFilterDetail.FilterColumn;
				_filterOperator = dlTemplateFilterDetail.FilterOperator;
				_filterValue = dlTemplateFilterDetail.FilterValue;
				_isActive = dlTemplateFilterDetail.IsActive;
				_isDelete = dlTemplateFilterDetail.IsDelete;
				_enteredBy = dlTemplateFilterDetail.EnteredBy;
				_enteredDate = dlTemplateFilterDetail.EnteredDate;
				_updatedBy = dlTemplateFilterDetail.UpdatedBy;
				_updatedDate = dlTemplateFilterDetail.UpdatedDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///Constructor using unique field(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///TemplateFilterDetailGUID
		///</parameters>
		public BLTemplateFilterDetail(string templateFilterDetailGUID)
		{
			try
			{
				DLTemplateFilterDetail dlTemplateFilterDetail = DLTemplateFilterDetail.SelectOneByTemplateFilterDetailGUID(templateFilterDetailGUID);
				_templateFilterDetailId = dlTemplateFilterDetail.TemplateFilterDetailId;
				_templateFilterDetailGUID = dlTemplateFilterDetail.TemplateFilterDetailGUID;
				_templateId = dlTemplateFilterDetail.TemplateId;
				_templateTableDetailId = dlTemplateFilterDetail.TemplateTableDetailId;
				_filterColumn = dlTemplateFilterDetail.FilterColumn;
				_filterOperator = dlTemplateFilterDetail.FilterOperator;
				_filterValue = dlTemplateFilterDetail.FilterValue;
				_isActive = dlTemplateFilterDetail.IsActive;
				_isDelete = dlTemplateFilterDetail.IsDelete;
				_enteredBy = dlTemplateFilterDetail.EnteredBy;
				_enteredDate = dlTemplateFilterDetail.EnteredDate;
				_updatedBy = dlTemplateFilterDetail.UpdatedBy;
				_updatedDate = dlTemplateFilterDetail.UpdatedDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLTemplateFilterDetail
		///</parameters>
		protected internal BLTemplateFilterDetail(DLTemplateFilterDetail dlTemplateFilterDetail)
		{
			try
			{
				_templateFilterDetailId = dlTemplateFilterDetail.TemplateFilterDetailId;
				_templateFilterDetailGUID = dlTemplateFilterDetail.TemplateFilterDetailGUID;
				_templateId = dlTemplateFilterDetail.TemplateId;
				_templateTableDetailId = dlTemplateFilterDetail.TemplateTableDetailId;
				_filterColumn = dlTemplateFilterDetail.FilterColumn;
				_filterOperator = dlTemplateFilterDetail.FilterOperator;
				_filterValue = dlTemplateFilterDetail.FilterValue;
				_isActive = dlTemplateFilterDetail.IsActive;
				_isDelete = dlTemplateFilterDetail.IsDelete;
				_enteredBy = dlTemplateFilterDetail.EnteredBy;
				_enteredDate = dlTemplateFilterDetail.EnteredDate;
				_updatedBy = dlTemplateFilterDetail.UpdatedBy;
				_updatedDate = dlTemplateFilterDetail.UpdatedDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new TemplateFilterDetail record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DLTemplateFilterDetail dlTemplateFilterDetail = new DLTemplateFilterDetail();
			RegisterDataObject(dlTemplateFilterDetail);
			BeginTransaction("savenewBLTemplateFilterDetail");
			try
			{
				dlTemplateFilterDetail.TemplateFilterDetailGUID = _templateFilterDetailGUID;
				dlTemplateFilterDetail.TemplateId = _templateId;
				dlTemplateFilterDetail.TemplateTableDetailId = _templateTableDetailId;
				dlTemplateFilterDetail.FilterColumn = _filterColumn;
				dlTemplateFilterDetail.FilterOperator = _filterOperator;
				dlTemplateFilterDetail.FilterValue = _filterValue;
				dlTemplateFilterDetail.IsActive = _isActive;
				dlTemplateFilterDetail.IsDelete = _isDelete;
				dlTemplateFilterDetail.EnteredBy = _enteredBy;
				dlTemplateFilterDetail.EnteredDate = _enteredDate;
				dlTemplateFilterDetail.UpdatedBy = _updatedBy;
				dlTemplateFilterDetail.UpdatedDate = _updatedDate;
				dlTemplateFilterDetail.Insert();
				CommitTransaction();
				
				_templateFilterDetailId = dlTemplateFilterDetail.TemplateFilterDetailId;
				_templateFilterDetailGUID = dlTemplateFilterDetail.TemplateFilterDetailGUID;
				_templateId = dlTemplateFilterDetail.TemplateId;
				_templateTableDetailId = dlTemplateFilterDetail.TemplateTableDetailId;
				_filterColumn = dlTemplateFilterDetail.FilterColumn;
				_filterOperator = dlTemplateFilterDetail.FilterOperator;
				_filterValue = dlTemplateFilterDetail.FilterValue;
				_isActive = dlTemplateFilterDetail.IsActive;
				_isDelete = dlTemplateFilterDetail.IsDelete;
				_enteredBy = dlTemplateFilterDetail.EnteredBy;
				_enteredDate = dlTemplateFilterDetail.EnteredDate;
				_updatedBy = dlTemplateFilterDetail.UpdatedBy;
				_updatedDate = dlTemplateFilterDetail.UpdatedDate;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLTemplateFilterDetail");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one TemplateFilterDetail record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BLTemplateFilterDetail
		///</parameters>
		public virtual void Update()
		{
			DLTemplateFilterDetail dlTemplateFilterDetail = new DLTemplateFilterDetail();
			RegisterDataObject(dlTemplateFilterDetail);
			BeginTransaction("updateBLTemplateFilterDetail");
			try
			{
				dlTemplateFilterDetail.TemplateFilterDetailId = _templateFilterDetailId;
				dlTemplateFilterDetail.TemplateFilterDetailGUID = _templateFilterDetailGUID;
				dlTemplateFilterDetail.TemplateId = _templateId;
				dlTemplateFilterDetail.TemplateTableDetailId = _templateTableDetailId;
				dlTemplateFilterDetail.FilterColumn = _filterColumn;
				dlTemplateFilterDetail.FilterOperator = _filterOperator;
				dlTemplateFilterDetail.FilterValue = _filterValue;
				dlTemplateFilterDetail.IsActive = _isActive;
				dlTemplateFilterDetail.IsDelete = _isDelete;
				dlTemplateFilterDetail.EnteredBy = _enteredBy;
				dlTemplateFilterDetail.EnteredDate = _enteredDate;
				dlTemplateFilterDetail.UpdatedBy = _updatedBy;
				dlTemplateFilterDetail.UpdatedDate = _updatedDate;
				dlTemplateFilterDetail.Update();
				CommitTransaction();
				
				_templateFilterDetailId = dlTemplateFilterDetail.TemplateFilterDetailId;
				_templateFilterDetailGUID = dlTemplateFilterDetail.TemplateFilterDetailGUID;
				_templateId = dlTemplateFilterDetail.TemplateId;
				_templateTableDetailId = dlTemplateFilterDetail.TemplateTableDetailId;
				_filterColumn = dlTemplateFilterDetail.FilterColumn;
				_filterOperator = dlTemplateFilterDetail.FilterOperator;
				_filterValue = dlTemplateFilterDetail.FilterValue;
				_isActive = dlTemplateFilterDetail.IsActive;
				_isDelete = dlTemplateFilterDetail.IsDelete;
				_enteredBy = dlTemplateFilterDetail.EnteredBy;
				_enteredDate = dlTemplateFilterDetail.EnteredDate;
				_updatedBy = dlTemplateFilterDetail.UpdatedBy;
				_updatedDate = dlTemplateFilterDetail.UpdatedDate;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBLTemplateFilterDetail");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one TemplateFilterDetail record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DLTemplateFilterDetail dlTemplateFilterDetail = new DLTemplateFilterDetail();
			RegisterDataObject(dlTemplateFilterDetail);
			BeginTransaction("deleteBLTemplateFilterDetail");
			try
			{
				dlTemplateFilterDetail.TemplateFilterDetailId = _templateFilterDetailId;
				dlTemplateFilterDetail.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBLTemplateFilterDetail");
				throw;
			}
		}
		
		///<Summary>
		///TemplateFilterDetailCollection
		///This method returns the collection of BLTemplateFilterDetail objects
		///</Summary>
		///<returns>
		///List[BLTemplateFilterDetail]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BLTemplateFilterDetail> TemplateFilterDetailCollection()
		{
			try
			{
				IList<BLTemplateFilterDetail> blTemplateFilterDetailCollection = new List<BLTemplateFilterDetail>();
				IList<DLTemplateFilterDetail> dlTemplateFilterDetailCollection = DLTemplateFilterDetail.SelectAll();
			
				foreach(DLTemplateFilterDetail dlTemplateFilterDetail in dlTemplateFilterDetailCollection)
					blTemplateFilterDetailCollection.Add(new BLTemplateFilterDetail(dlTemplateFilterDetail));
			
				return blTemplateFilterDetailCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///TemplateFilterDetailCollectionCount
		///This method returns the collection count of BLTemplateFilterDetail objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 TemplateFilterDetailCollectionCount()
		{
			try
			{
				Int32 objCount = DLTemplateFilterDetail.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BLTemplateFilterDetail>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DLTemplateFilterDetail.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///TemplateFilterDetailCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BLTemplateFilterDetail objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> blTemplateFilterDetailCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DLTemplateFilterDetail> dlTemplateFilterDetailCollection = DLTemplateFilterDetail.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DLTemplateFilterDetail resdlTemplateFilterDetail in dlTemplateFilterDetailCollection)
					blTemplateFilterDetailCollection.Add((T)(object)new BLTemplateFilterDetail(resdlTemplateFilterDetail));
			
				return blTemplateFilterDetailCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///TemplateFilterDetailCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BLTemplateFilterDetail objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DLTemplateFilterDetail.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? TemplateFilterDetailId
		{
			get
			{
				 return _templateFilterDetailId;
			}
			set
			{
				_templateFilterDetailId = value;
				_isDirty = true;
			}
		}
		
		public virtual string TemplateFilterDetailGUID
		{
			get
			{
				 return _templateFilterDetailGUID;
			}
			set
			{
				_templateFilterDetailGUID = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? TemplateId
		{
			get
			{
				 return _templateId;
			}
			set
			{
				_templateId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? TemplateTableDetailId
		{
			get
			{
				 return _templateTableDetailId;
			}
			set
			{
				_templateTableDetailId = value;
				_isDirty = true;
			}
		}
		
		public virtual string FilterColumn
		{
			get
			{
				 return _filterColumn;
			}
			set
			{
				_filterColumn = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? FilterOperator
		{
			get
			{
				 return _filterOperator;
			}
			set
			{
				_filterOperator = value;
				_isDirty = true;
			}
		}
		
		public virtual string FilterValue
		{
			get
			{
				 return _filterValue;
			}
			set
			{
				_filterValue = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsActive
		{
			get
			{
				 return _isActive;
			}
			set
			{
				_isActive = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsDelete
		{
			get
			{
				 return _isDelete;
			}
			set
			{
				_isDelete = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? EnteredBy
		{
			get
			{
				 return _enteredBy;
			}
			set
			{
				_enteredBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? EnteredDate
		{
			get
			{
				 return _enteredDate;
			}
			set
			{
				_enteredDate = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UpdatedBy
		{
			get
			{
				 return _updatedBy;
			}
			set
			{
				_updatedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? UpdatedDate
		{
			get
			{
				 return _updatedDate;
			}
			set
			{
				_updatedDate = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
